hydroblock2.0 driver
CIDCO-dev/MBES-lib pull request #258
Opened 2022-08-02 14:12 UTC by patcmorneau

2022-08-08 18:24 UTC, patcmorneau commented
/MBES-lib$ ./build/bin/georeference -g src/hydroblock/data/
only output NaN

2022-08-10 16:55 UTC, patcmorneau commented
the command i use : ./build/bin/georeference -g -s test/data/SVP/SVP.txt  src/hydroblock/data/

the command was working with the previous commit but since the change it wont parse the three file

line 41 in hydroblock20Parser don't show in the stderr

2022-08-24 16:13 UTC, patcmorneau commented
still not quite sure what to do with 
`printer.processSwathStart(1450); `
since without it , it only output NaNs

2022-09-06 15:59 UTC, glabmoris requested changes

2022-09-06 15:59 UTC, glabmoris commented on src/hydroblock/Hydroblock20Parser.cpp
> +	FILE *gnssFile, *imuFile, *sonarFile;
Use c++ ifstream instead

2022-09-06 15:59 UTC, glabmoris commented on src/hydroblock/Hydroblock20Parser.cpp
> +	while(true){
Use 3 loops, one for each file

2022-09-06 15:59 UTC, glabmoris commented on src/hydroblock/Hydroblock20Parser.cpp
> +		if(fgets(imuBuff, 49, imuFile)){
fgets is generally a very bad idea safety-wise because of buffer management. The safest pattern is to use ifstream and std::getline() into a c++ string (let's call it s), then to use sscanf() on s.c_str() to avoid robust parsing/buffer overflow issues.

2022-09-07 19:09 UTC, glabmoris requested changes

2022-09-07 19:09 UTC, glabmoris commented on src/hydroblock/Hydroblock20Parser.cpp
> +				sscanf(row.c_str(), "%d-%d-%d %d:%d:%d.%d;%lf;%lf;%lf;%d;%d",
Verifier la valeur de retour de sscanf qui devrait être 12. Si ce n'Est pas 12, c'est le header (et on skippe)

2022-09-13 19:40 UTC, merged